server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://localhost:3336/OnlinePetShop
#    url: jdbc:mysql://db:3306/OnlinePetShop
    url: jdbc:mysql://34.172.183.145:3306/OnlinePetShop
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  private-key: CLp/edt3SGCOs7+ByILRGWPR5N168VSi8TG12KBe2/Y=