server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/OnlinePetShop
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  private-key: CLp/edt3SGCOs7+ByILRGWPR5N168VSi8TG12KBe2/Y=

