server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://34.172.183.145:3306/OnlinePetShop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    private-key: CLp/edt3SGCOs7+ByILRGWPR5N168VSi8TG12KBe2/Y=

